#!/usr/bin/env python3
"""
Prepare the final Circos karyotype labels and synteny-mirrored chromosome colors.

The input karyotype is expected to use standard Circos lines:
    chr - chr_id label start end color

Chromosome colors use alternating Population 1 dark/light blue and Population 2
dark/light orange, keyed to the CCMP1545 synteny anchor chromosome index.
Hex colors are converted to generated Circos color names and written to a
companion colors file.
"""

import argparse
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR.parent))

from figure_color_guide import (
    DEFAULT_GUIDE_PATH,
    build_synteny_mirrored_chr_colors,
    load_color_guide,
)


HEX_COLOR_RE = re.compile(r"^#?([0-9a-fA-F]{6})$")


def parse_args():
    parser = argparse.ArgumentParser(description="Format Circos karyotype labels and colors")
    parser.add_argument("--input", required=True, help="Input karyotype")
    parser.add_argument("--output", required=True, help="Output karyotype")
    parser.add_argument("--colors-output", required=True, help="Generated Circos color definitions")
    parser.add_argument("--links", required=True, help="Synteny links TSV used for color mirroring")
    parser.add_argument("--strain1-name", required=True, help="First strain name, e.g. CCMP1545")
    parser.add_argument("--strain2-name", required=True, help="Second strain name, e.g. RCC1749")
    parser.add_argument(
        "--color-guide",
        default=str(DEFAULT_GUIDE_PATH),
        help="Master figure color guide TSV",
    )
    return parser.parse_args()


def display_label(label):
    """Remove strain prefixes from labels while preserving the chromosome name."""
    if "-" in label:
        return label.split("-", 1)[1]
    return label


def strain_for_chr_id(chr_id, strain1_name, strain2_name):
    if chr_id.startswith(strain1_name):
        return strain1_name
    if chr_id.startswith(strain2_name):
        return strain2_name
    return None


def circos_color_name(chr_id):
    safe = re.sub(r"[^A-Za-z0-9]+", "_", chr_id).strip("_").lower()
    return f"chr_{safe}"


def parse_color(value, color_key, generated_colors):
    """Return the karyotype color token, adding hex definitions when needed."""
    value = str(value).strip()
    if not value:
        return None

    match = HEX_COLOR_RE.match(value)
    if not match:
        return value

    hex_value = match.group(1)
    rgb = tuple(int(hex_value[i : i + 2], 16) for i in (0, 2, 4))
    generated_colors[color_key] = rgb
    return color_key


def read_karyotype_entries(path, strain1_name, strain2_name):
    entries = []
    with open(path) as handle:
        for line in handle:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue

            parts = stripped.split()
            if len(parts) < 7 or parts[0] != "chr" or parts[1] != "-":
                continue

            chr_id = parts[2]
            label = parts[3]
            entries.append(
                {
                    "chr_id": chr_id,
                    "label": label,
                    "strain": strain_for_chr_id(chr_id, strain1_name, strain2_name),
                    "parts": parts,
                }
            )
    return entries


def build_circos_color_tokens(chr_colors):
    generated_colors = {}
    tokens = {}
    for chr_id, hex_color in chr_colors.items():
        color_key = circos_color_name(chr_id)
        token = parse_color(hex_color, color_key, generated_colors)
        if token:
            tokens[chr_id] = token
    return tokens, generated_colors


def write_colors(path, generated_colors):
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as handle:
        handle.write("# Generated by format_circos_karyotype.py\n")
        if not generated_colors:
            handle.write("# No hex palette colors supplied.\n")
            return

        for name, rgb in sorted(generated_colors.items()):
            handle.write(f"{name} = {rgb[0]},{rgb[1]},{rgb[2]}\n")


def format_karyotype(input_path, output_path, color_tokens, strain1_name, strain2_name):
    with open(input_path) as source, open(output_path, "w") as dest:
        for line in source:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                dest.write(line)
                continue

            parts = stripped.split()
            if len(parts) < 7 or parts[0] != "chr" or parts[1] != "-":
                dest.write(line)
                continue

            chr_id = parts[2]
            parts[3] = display_label(parts[3])
            color = color_tokens.get(chr_id)
            if color:
                parts[6] = color

            dest.write(" ".join(parts) + "\n")


def main():
    args = parse_args()
    entries = read_karyotype_entries(args.input, args.strain1_name, args.strain2_name)
    labels = {entry["chr_id"]: entry["label"] for entry in entries}
    strains = {entry["chr_id"]: entry["strain"] for entry in entries}
    guide_colors = load_color_guide(args.color_guide)
    chr_colors = build_synteny_mirrored_chr_colors(
        args.links,
        [entry["chr_id"] for entry in entries],
        labels,
        strains,
        args.strain1_name,
        args.strain2_name,
        guide=guide_colors,
    )
    color_tokens, generated_colors = build_circos_color_tokens(chr_colors)
    format_karyotype(args.input, args.output, color_tokens, args.strain1_name, args.strain2_name)
    write_colors(args.colors_output, generated_colors)


if __name__ == "__main__":
    main()
